openapi: 3.0.0
servers:
  - description: server
    url: http://localhost:4000/api
info: 
  title: API GERSA
  version: 1.0.0
tags:
- name: users
  description: Access, update users information
- name: employees
  description: Access, update employee information
- name: contracts
  description: Access, update contracts information
- name: check
  description: Get the status of code and check
- name: logbooks
  description: Save users logs activity 
paths: 
  /users/{id}:
    get:
      tags:
      - users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      security:
        - bearerAuth: []
    patch: 
      tags:
      - users
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
      - name: id
        in: path
        description: name that need to be updated
        required: true
        schema:
          type: string
      responses:
        '204':
          description: successful operation
        '400':
          description: Invalid user supplied
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: User not found
      security:
        - bearerAuth: []
  /users/authenticate:
    post:
      tags: 
      - users
      summary: Logs user into the system
      responses:
        '200':
          description: User finded 
        '400':
          description: Usuario o contraseña incorrecta
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLog"
  /users:
    post:
      tags:
      - users
      summary: Create user
      responses:
        '200':
          description: User finded 
        '400':
          description: Usuario o contraseña incorrecta
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        
  /contracts/:
    post:
      tags:
      - contracts
      summary: Inserta la informacion de un nuevo contrato
      
      requestBody: 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodyContratosPost'
        required: true
      responses:
        200:
          description: (OK) Registro exitoso
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/BodyContratosResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
      security:
        - bearerAuth: []
  /contracts/{idUsuario}:
    get:
      tags:
      - contracts
      summary: Obtiene la informacion de la base de datos de los contratos de un empleado
      parameters:
      - name: idUsuario
        in: path
        description: Identificador de los contratos a obtener
        required: true
        schema:
          type: integer
      
      
      responses:
        200:
          description: (OK) La informacion de los contratos se obtuvo de forma exitosa
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/ExitoContratosGet'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
      security:
        - bearerAuth: []
  
  /check:
    get:
      tags:
      - check
      parameters:
        - name: accessCode
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User finded
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFound'
  /logbook/{userId}:
    get:
      tags:
      - logbooks
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Logbook of user
      security:
        - bearerAuth: []
  /logbook:
    post:
      tags:
      - logbooks
      parameters:
        - name: operation
          in: query
          required: true
          schema:
            type: string
        - name: code
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Log Creado
  
components: 
  responses:
    UnauthorizedError:
      description: (Unauthorized) Usuario no autorizado
      
    NotFound:
      description: (Not Found) No se encontro la informacion
      
    BadRequest:
      description: (Bad Request) No se encontro la informacion
    
    ServerError:
      description: Error en el servidor
      
  parameters:
    token: 
          name: token
          in: header
          description: Token de auntentificacion
          required: true
          schema:
            type: integer    
            
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes

  schemas:
    UserLog:
      type: object
      properties:
        username:
          type: string
          example: "prueba@prueba.com"
        password:
          type: string
          example: "prueba"
      xml:
        name: UserLog
    User:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
        phone:
          type: string
        sendInvitation: 
          type: boolean
    Logbook:
      type: object
      properties:
        userid:
          type: string
        username:
          type: string
    BodyContratosPost:
      type: object
      properties:
        userId:
         type: integer
         description: Id del usuario
        tipoDeContrato:
         type: string
         description: Tipo de contrato
        puesto:
         type: string
         description: Nombre del puesto
        fechaDeInicio:
         type: string
         description: Fecha de inicio de contrato
        fechaDeFinalizacion:
         type: string
         description: Fecha de finalizacion de contrato
        horasLaborales:
         type: integer
         description: Horas laborales del contrato
        unidadLaborales:
         type: string
         description: tipo de unidad para laborales(semana, quinciena, mes)
        lunes:
         type: boolean
         description: Bandera para definir si se trabaja el dia Lunes
        martes:
         type: boolean
         description: Bandera para definir si se trabaja el dia Martes
        miercoles:
         type: boolean
         description: Bandera para definir si se trabaja el dia Miercoles
        jueves:
         type: boolean
         description: Bandera para definir si se trabaja el dia Jueves
        viernes:
         type: boolean
         description: Bandera para definir si se trabaja el dia Viernes
        sabado:
         type: boolean
         description: Bandera para definir si se trabaja el dia Sabado
        domingo:
         type: boolean
         description: Bandera para definir si se trabaja el dia Domingo
        tipoSalario:
         type: string
         description: tipo de unidad para laborales(semana, quinciena, mes)
        cantidadSalario:
         type: integer
         description: Salario definido en el contrato
         
    BodyContratosResponse:
      type: object
      properties:
        message:
         type: string
         description: Usuario no autorizado
        ok:
         type: boolean
         description: (True) Salio bien, (False) Algo salio mal
    
    ExitoContratosGet:
      type: object
      properties:
        id:
         type: integer
         description: Id del contrato
        userId:
         type: integer
         description: Id del usuario
        tipoDeContrato:
         type: string
         description: Tipo de contrato
        puesto:
         type: string
         description: Nombre del puesto
        fechaDeInicio:
         type: string
         description: Fecha de inicio de contrato
        fechaDeFinalizacion:
         type: string
         description: Fecha de finalizacion de contrato
        horasLaborales:
         type: integer
         description: Horas laborales del contrato
        unidadLaborales:
         type: string
         description: tipo de unidad para laborales(semana, quinciena, mes)
        lunes:
         type: boolean
         description: Bandera para definir si se trabaja el dia Lunes
        martes:
         type: boolean
         description: Bandera para definir si se trabaja el dia Martes
        miercoles:
         type: boolean
         description: Bandera para definir si se trabaja el dia Miercoles
        jueves:
         type: boolean
         description: Bandera para definir si se trabaja el dia Jueves
        viernes:
         type: boolean
         description: Bandera para definir si se trabaja el dia Viernes
        sabado:
         type: boolean
         description: Bandera para definir si se trabaja el dia Sabado
        domingo:
         type: boolean
         description: Bandera para definir si se trabaja el dia Domingo
        tipoSalario:
         type: string
         description: tipo de unidad para laborales(semana, quinciena, mes)
        cantidadSalario:
         type: integer
         description: Salario definido en el contrato
        isContractActivide:
         type: boolean
         description: Bandera para definir si el contrato esta activo
      
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'